Change method of getting protoc

diff --git a/.github/workflows/build-go.yml b/.github/workflows/build-go.yml
--- a/.github/workflows/build-go.yml
+++ b/.github/workflows/build-go.yml
@@ -55,21 +55,38 @@ jobs:
 
     - name: Set up protoc
       if: ${{ env.proto == 'true' }}
-      uses: arduino/setup-protoc@v3
-
-    - name: Set up protoc plugins
-      if: ${{ env.proto == 'true' }}
       run: |
+        # Fetch protobuf release info.
+        RELEASE="$(curl -s -m10 --connect-timeout 5 \
+          https://api.github.com/repos/protocolbuffers/protobuf/releases/latest)"
+        ASSETS="$(jq '.assets | map(select(.browser_download_url | test("protoc.*linux-x86_64")))')"
+        [ "$(jq length <<< "$ASSETS")" -eq 1 ] || exit 1
+        # Download and unarchive the release.
+        DOWNLOAD_URL="$(jq -r ".[0].browser_download_url" <<< "$ASSETS")"
+        wget "$DOWNLOAD_URL"
+        echo ":arrow_down: Downloaded $DOWNLOAD_URL" >> $GITHUB_STEP_SUMMARY
+        if grep -q '\.zip$' <<< "$DOWNLOAD_URL"; then
+          unzip "$(basename "$DOWNLOAD_URL")"
+        elif grep -q '\.tar.gz$' <<< "$DOWNLOAD_URL"; then
+          tar -xvf "$(basename "$DOWNLOAD_URL")"
+        else
+          echo "::error file=$F::unknown file format for $(basename "$DOWNLOAD_URL")"
+          exit 1
+        fi
+        # Add to path, assuming archive contains file "bin/protoc".
+        export PATH="$(pwd)/bin:$PATH"
+        # Get protoc plugins.
         go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
         go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
         export PATH="$(go env GOPATH)/bin:$PATH"
+        # Print version information.
+        for BIN in protoc protoc-gen-go protoc-gen-go-grpc; do
+          echo ":information_source: $BIN version $($BIN --version | grep -o '[0-9.]\+$')" >> $GITHUB_STEP_SUMMARY
+        done
 
     - name: Compile proto files
       if: ${{ env.proto == 'true' }}
       run: |
-        for BIN in protoc protoc-gen-go protoc-gen-go-grpc; do
-          echo ":information_source: $BIN version $($BIN --version | grep -o '[0-9.]\+$')" >> $GITHUB_STEP_SUMMARY
-        done
         find . -name "*.proto" -exec \
           protoc --go_out=. --go_opt=paths=source_relative \
           --go-grpc_out=. --go-grpc_opt=paths=source_relative {} \;
