Update update-deployment-repository.yml

diff --git a/.github/workflows/update-deployment-repository.yml b/.github/workflows/update-deployment-repository.yml
--- a/.github/workflows/update-deployment-repository.yml
+++ b/.github/workflows/update-deployment-repository.yml
@@ -27,11 +27,13 @@ jobs:
     - name: Update deployment repository
       run: |
         COMMIT_FILE="${{ inputs.service }}/commit"
-        echo "OLD_COMMIT=(none)" >> $GITHUB_ENV
-        [ -f "$COMMIT_FILE" ] && echo "OLD_COMMIT=$(cat "$COMMIT_FILE")" >> $GITHUB_ENV
-        if [ "$OLD_COMMIT" = "${{ inputs.commit }}" ]; then
-          echo "::error ::New commit is same as current commit"
-          exit 1
+        OLD_COMMIT="(none)"
+        if [ -f "$COMMIT_FILE" ]; then
+          OLD_COMMIT="$(cat "$COMMIT_FILE")"
+          if [ "$OLD_COMMIT" = "${{ inputs.commit }}" ]; then
+            echo "::error ::New commit is same as current commit"
+            exit 1
+          fi
         fi
         echo "::notice ::Updating commit for ${{ inputs.service }} from ${{ OLD_COMMIT }} to ${{ inputs.commit }}"
         git config user.email "githubaction@dummy.com"
